name: number_trivia
description: A demo Flutter project to demonstrate Clean Architecture.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # value equality
  equatable: ^0.6.1
  # functional programming
  dartz: ^0.8.7
  data_connection_checker: ^0.3.4
  shared_preferences: ^0.5.4
  http: ^0.12.0+2
  bloc: ^1.0.0
  get_it: ^3.0.3
  flutter_bloc: ^1.0.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1


flutter:
  uses-material-design: true
